version: '3'
services:
    database:
        image: mongo
        ports:
            - 27017:27017
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        command: sh -c 'npm ci && npm start'
        ports:
            - 3000:3000
        depends_on:
            - database
    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/frontend
        command: sh -c 'npm ci && npm start'
        ports:
            - 8080:8080
        depends_on:
            - backend
